"""
Django settings for adsserver project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- Minimal .env loader (no external dependency) — values never committed to git. ---
_env_file = BASE_DIR / '.env'
if _env_file.exists():
    for _line in _env_file.read_text().splitlines():
        _line = _line.strip()
        if _line and not _line.startswith('#') and '=' in _line:
            _k, _v = _line.split('=', 1)
            os.environ.setdefault(_k.strip(), _v.strip())


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret! (from .env)
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-dev-only-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', '*').split(',')

# HTTPS behind nginx (production): trust the proxy's scheme header and allow the
# public origin(s) for CSRF. Both are no-ops unless set in .env.
if os.environ.get('CSRF_TRUSTED_ORIGINS'):
    CSRF_TRUSTED_ORIGINS = os.environ['CSRF_TRUSTED_ORIGINS'].split(',')
if os.environ.get('BEHIND_TLS_PROXY', 'False') == 'True':
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'ads',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'adsserver.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'adsserver.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# PostgreSQL in production (when POSTGRES_DB is set via .env); SQLite for local dev.
if os.environ.get('POSTGRES_DB'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ['POSTGRES_DB'],
            'USER': os.environ.get('POSTGRES_USER', 'adsuser'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', ''),
            'HOST': os.environ.get('POSTGRES_HOST', '127.0.0.1'),
            'PORT': os.environ.get('POSTGRES_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Schedule evaluation timezone — ad time slots (8–10 AM) are interpreted in this zone
SCHEDULE_TZ = 'Asia/Kolkata'

# Fleet monitoring — seconds since last heartbeat that define each status.
# online: <= DEVICE_ONLINE_SECONDS ; warning: <= DEVICE_WARNING_SECONDS ; else offline
DEVICE_ONLINE_SECONDS = 30
DEVICE_WARNING_SECONDS = 300


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'mediafiles'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# JWT settings
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=8),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
}

# CORS — allow React dev server and same-host requests
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'http://localhost:3000',
]
CORS_ALLOW_ALL_ORIGINS = True  # set to False and use CORS_ALLOWED_ORIGINS in production

# File upload size limit (200 MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 209715200
FILE_UPLOAD_MAX_MEMORY_SIZE = 209715200

# Station Data API
STATION_DATA_API_URL   = 'https://smartnetwork.azure-api.net/station-data/api/v2/StationAlert/Report'
DEVICE_ONLINE_SECONDS  = 30
DEVICE_WARNING_SECONDS = 300

# Swap data API (for ad-impression estimates). Same Bearer auth as the StationAlert API.
SWAP_API_URL = 'https://smartnetwork.azure-api.net/station-data/api/Swap/SwapReport'
SWAP_API_FILTER = 1   # filter value passed to SwapReport (per the API's expected payload)
# Customer dwell time at the screen, by number of battery packs in the swap (seconds).
# Midpoints of the measured ranges 1–2 / 2–3 / 3–4 min; tune from real measurement.
DWELL_SECONDS_BY_BP = {1: 90, 2: 150, 3: 210}
DWELL_SECONDS_DEFAULT = 90
# Count failed swap attempts too (the customer was still present at the screen).
IMPRESSIONS_COUNT_FAILED_SWAPS = True

# Station API auth — OAuth2 client-credentials. ads/sn_auth.py mints and caches the
# Bearer token automatically (refreshing before expiry), so no manual token is needed.
# Values copied from the CCU's station_api_configurations.json ("azure-auth-api"); the
# resource/audience matches what the StationAlert API validates.
STATION_AUTH_URL           = 'https://login.microsoftonline.com/98fd8132-b015-4e55-8d37-09bc8122e2ac/oauth2/token'
STATION_AUTH_CLIENT_ID     = '6cf68dd7-3d13-4aa9-8819-c2ed3758a6f8'
# Secret is loaded from .env / environment — never hardcoded/committed.
STATION_AUTH_CLIENT_SECRET = os.environ.get('STATION_AUTH_CLIENT_SECRET', '')
STATION_AUTH_SCOPE         = 'Users.Read'
STATION_AUTH_RESOURCE      = 'api://6cf68dd7-3d13-4aa9-8819-c2ed3758a6f8'

# EMERGENCY OVERRIDE ONLY — auto-mint above is the primary path. If you ever need to
# force a specific token (e.g. mint endpoint down), set the STATION_DATA_API_TOKEN env
# var or drop a raw token into station_token.txt. A leading "Bearer " is stripped.
# When empty, sn_auth ignores it and uses the minted token.
_token_override = os.environ.get('STATION_DATA_API_TOKEN')
if not _token_override:
    _token_file = BASE_DIR / 'station_token.txt'
    if _token_file.exists():
        _token_override = _token_file.read_text()
STATION_DATA_API_TOKEN = _token_override.strip().removeprefix('Bearer').strip() if _token_override else ''
