# Generated by Django 5.2.12 on 2026-06-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admedia',
            name='target_type',
            field=models.CharField(choices=[('zone', 'Zone'), ('station', 'Station')], default='zone', max_length=10),
        ),
        migrations.AddField(
            model_name='admedia',
            name='targets',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
