# Generated by Django 5.2.12 on 2026-06-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_admedia_target_type_admedia_targets'),
    ]

    operations = [
        migrations.AddField(
            model_name='admedia',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
