# Generated by Django 5.2.12 on 2026-06-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_admedia_file_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='admedia',
            name='daily_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admedia',
            name='daily_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admedia',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admedia',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
