# Generated by Django 5.2.12 on 2026-06-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_admedia_daily_end_time_admedia_daily_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admedia',
            name='slot',
            field=models.CharField(blank=True, choices=[('top_left', 'Top Left'), ('top_right', 'Top Right'), ('bottom_left', 'Bottom Left'), ('bottom_right', 'Bottom Right')], default='', max_length=12),
        ),
    ]
