# Generated by Django 5.2.12 on 2026-06-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_admedia_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaybackSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=64)),
                ('zone', models.CharField(blank=True, max_length=64)),
                ('station', models.CharField(blank=True, max_length=64)),
                ('active_ads', models.JSONField()),
                ('started_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['device_id', 'last_seen_at'], name='ads_playbac_device__952242_idx')],
            },
        ),
    ]
