# Generated by Django 5.2.12 on 2026-06-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_playbacksnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.PositiveSmallIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
