# Generated by Django 5.2.12 on 2026-07-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_displayconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.PositiveSmallIntegerField()),
                ('target_type', models.CharField(default='zone', max_length=10)),
                ('targets', models.JSONField(default=list)),
                ('assignments', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
